// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5U8YwW-wVom6Z691woDEFPVSaOuf2W3w',
    appId: '1:280716781618:web:21c18a79026f41e37a342b',
    messagingSenderId: '280716781618',
    projectId: 'personal-portfolio-5dad9',
    authDomain: 'personal-portfolio-5dad9.firebaseapp.com',
    storageBucket: 'personal-portfolio-5dad9.firebasestorage.app',
    measurementId: 'G-J75GC20HQ8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5U8YwW-wVom6Z691woDEFPVSaOuf2W3w',
    appId: '1:280716781618:web:21c18a79026f41e37a342b',
    messagingSenderId: '280716781618',
    projectId: 'personal-portfolio-5dad9',
    authDomain: 'personal-portfolio-5dad9.firebaseapp.com',
    storageBucket: 'personal-portfolio-5dad9.firebasestorage.app',
    measurementId: 'G-J75GC20HQ8',
  );
}
